import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "./ChatProvider";
import { cn } from "@/lib/utils";
import LogoText from "./home/LogoText";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-gradient-to-b from-gray-950 to-gray-900 text-white",
          `${geistSans.variable} ${geistMono.variable} antialiased`
        )}
      >
        <LogoText />
        <div className="py-0 h-screen overflow-hidden">
          <ChatProvider>
            {/* <StateAnimations /> */}
            {children}
          </ChatProvider>
        </div>
      </body>
    </html>
  );
}
